version: "3"

services:
  demo-spring-boot:
    image: dperezcabrera/demo-spring-boot:0.0.1
    environment:
      APP_URL: "http://localhost:30000"
      DB_URL: "${DB_URL}"
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DRIVER: org.hibernate.dialect.PostgreSQLDialect
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - 30000:8080
    networks:
      - demo-network

  demo-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - demo-postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - demo-network

volumes:
  demo-postgres-data:

networks:
  demo-network:
