apiVersion: v1
kind: Secret
metadata:
  name: demo-secrets
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ=
  JWT_SECRET: MTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEx

