apiVersion: v1
kind: List
items:
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: demo-spring-boot
    annotations:
      app: demo
  spec:
    minReplicas: 2
    maxReplicas: 8
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: demo-spring-boot
    targetCPUUtilizationPercentage: 65
