apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: demo-postgres-data
    app: demo
  name: demo-postgres-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
