apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-monitor
spec:
  selector:
    matchLabels:
      app: demo
  endpoints:
  - port: http-traffic
    path: "/actuator/prometheus"
