apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-spring-boot-config-map
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
data:
  application.yaml: |-
    spring:
        datasource:
            hikari:
                connectionTimeout: 20000
                maximumPoolSize: 5
            sqlScriptEncoding: UTF-8
            url: ${DB_URL}
            username: ${DB_USERNAME}
            password: ${DB_PASSWORD}
        jmx:
            enabled: false
        jpa:
            database-platform: ${DB_DRIVER}
            hibernate:
                ddl-auto: update
            open-in-view: false
            properties:
                hibernate:
                    jdbc:
                        lob:
                            non_contextual_creation: true
                    temp:
                        use_jdbc_metadata_defaults: false
        main:
            lazy-initialization: true

    logging:
        file:
            name: logs/app.log
        level:
            root: info
            com.example.demo: debug
            org.springframework.web: error
        pattern:
            console: '%-4relative [%thread] %-5level %logger{35} - %msg %n'
            dateformat: yyyy-MM-dd HH:mm:ss.SSS

    jwt:
        token:
            secret: ${JWT_SECRET}
            expiration-days: 7

    app:
        url: ${APP_URL}

    management:
        security:
            enabled: false
        server:
            port: 8081
        endpoints:
            web:
                exposure:
                    include: "*"
