scrape_configs:
  - job_name: 'prometheus-docker-discovery'  # This is a default value, it is mandatory.
    file_sd_configs:
    - files:
      - /discovery/targets.json
    relabel_configs:
    - source_labels: [__address__]
      regex:  '[^/]+(/.*)'            # capture '/...' part
      target_label: __metrics_path__  # change metrics path
    - source_labels: [__address__]
      regex:  '([^/]+)/.*'            # capture host:port
      target_label: __address__       # change target
